version: '3'

services:
  node:
    build: ./
    ports:
     - "80:8080"
    depends_on:
     - db
    environment:
      - MYSQL_HOST=db
    networks:
      - app-network
  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
